export enum Role {
  MEDIA_MANAGER = 'MEDIA_MANAGER',
  TECHNICAL_MANAGER = 'TECHNICAL_MANAGER',
  STAFF = 'STAFF',
}

export enum ClientStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  ON_HOLD = 'ON_HOLD',
  ARCHIVED = 'ARCHIVED',
}

export enum BrandStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  ARCHIVED = 'ARCHIVED',
}

export enum ProductStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  ARCHIVED = 'ARCHIVED',
}

export enum ShootType {
  INDOOR = 'INDOOR',
  OUTDOOR = 'OUTDOOR',
}

export enum Priority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum ProjectStatus {
  DRAFT = 'DRAFT',
  PLANNED = 'PLANNED',
  READY_FOR_PRODUCTION = 'READY_FOR_PRODUCTION',
  IN_PROGRESS = 'IN_PROGRESS',
  WAITING_FOR_TECHNICAL_REVIEW = 'WAITING_FOR_TECHNICAL_REVIEW',
  WAITING_FOR_MEDIA_REVIEW = 'WAITING_FOR_MEDIA_REVIEW',
  WAITING_FOR_CLIENT_CONFIRMATION = 'WAITING_FOR_CLIENT_CONFIRMATION',
  CLIENT_REVISION_REQUESTED = 'CLIENT_REVISION_REQUESTED',
  COMPLETED = 'COMPLETED',
  CLOSED = 'CLOSED',
  ARCHIVED = 'ARCHIVED',
  CANCELLED = 'CANCELLED',
}

export enum StudioBookingStatus {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  CANCELLED = 'CANCELLED',
}

export enum PermissionStatus {
  NOT_REQUIRED = 'NOT_REQUIRED',
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum WeatherStatus {
  FAVORABLE = 'FAVORABLE',
  RISK_RAIN = 'RISK_RAIN',
  EXTREME_HEAT = 'EXTREME_HEAT',
  POOR_LIGHT = 'POOR_LIGHT',
}

export enum ScriptStatus {
  DRAFT = 'DRAFT',
  READY = 'READY',
  ASSIGNED = 'ASSIGNED',
  IN_PRODUCTION = 'IN_PRODUCTION',
  WAITING_FOR_TECHNICAL_REVIEW = 'WAITING_FOR_TECHNICAL_REVIEW',
  WAITING_FOR_MEDIA_REVIEW = 'WAITING_FOR_MEDIA_REVIEW',
  WAITING_FOR_CLIENT_CONFIRMATION = 'WAITING_FOR_CLIENT_CONFIRMATION',
  CLIENT_REVISION_REQUESTED = 'CLIENT_REVISION_REQUESTED',
  COMPLETED = 'COMPLETED',
  CLOSED = 'CLOSED',
  CANCELLED = 'CANCELLED',
}

export enum GraphicReqStatus {
  DRAFT = 'DRAFT',
  READY = 'READY',
  ASSIGNED = 'ASSIGNED',
  IN_PRODUCTION = 'IN_PRODUCTION',
  WAITING_FOR_TECHNICAL_REVIEW = 'WAITING_FOR_TECHNICAL_REVIEW',
  WAITING_FOR_MEDIA_REVIEW = 'WAITING_FOR_MEDIA_REVIEW',
  WAITING_FOR_CLIENT_CONFIRMATION = 'WAITING_FOR_CLIENT_CONFIRMATION',
  CLIENT_REVISION_REQUESTED = 'CLIENT_REVISION_REQUESTED',
  COMPLETED = 'COMPLETED',
  CLOSED = 'CLOSED',
  CANCELLED = 'CANCELLED',
}

export enum TaskStatus {
  PENDING = 'PENDING',
  ASSIGNED = 'ASSIGNED',
  ACCEPTED = 'ACCEPTED',
  IN_PROGRESS = 'IN_PROGRESS',
  ON_HOLD = 'ON_HOLD',
  WAITING_FOR_REVIEW = 'WAITING_FOR_REVIEW',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum EquipmentAvailability {
  AVAILABLE = 'AVAILABLE',
  RESERVED = 'RESERVED',
  ISSUED = 'ISSUED',
  MAINTENANCE = 'MAINTENANCE',
  DAMAGED = 'DAMAGED',
  RETIRED = 'RETIRED',
}

export enum MaintenanceStatus {
  OPERATIONAL = 'OPERATIONAL',
  NEEDS_SERVICE = 'NEEDS_SERVICE',
  UNDER_REPAIR = 'UNDER_REPAIR',
  DECOMMISSIONED = 'DECOMMISSIONED',
}

export enum EquipmentMovementAction {
  ISSUED = 'ISSUED',
  USED = 'USED',
  RETURNED = 'RETURNED',
}

export enum AttendanceStatus {
  PRESENT = 'PRESENT',
  LATE = 'LATE',
  HALF_DAY = 'HALF_DAY',
  ABSENT = 'ABSENT',
}

export enum ApprovalType {
  TECHNICAL_REVIEW = 'TECHNICAL_REVIEW',
  MEDIA_REVIEW = 'MEDIA_REVIEW',
  CLIENT_CONFIRMATION = 'CLIENT_CONFIRMATION',
}

export enum ApprovalStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum ClientDecision {
  APPROVED = 'APPROVED',
  REVISION_REQUESTED = 'REVISION_REQUESTED',
  REJECTED = 'REJECTED',
}

export enum CommunicationType {
  INFORMATION = 'INFORMATION',
  QUESTION = 'QUESTION',
  CLARIFICATION = 'CLARIFICATION',
  REQUIREMENT = 'REQUIREMENT',
  APPROVAL_REQUEST = 'APPROVAL_REQUEST',
  REVIEW_COMMENT = 'REVIEW_COMMENT',
  ISSUE_REPORT = 'ISSUE_REPORT',
  BLOCKER = 'BLOCKER',
  ANNOUNCEMENT = 'ANNOUNCEMENT',
  GENERAL_NOTE = 'GENERAL_NOTE',
}
