import { Role, PermissionType, ModuleType } from '../enums';

/**
 * Declares which permission types each module supports based on operational requirements.
 */
export const MODULE_SUPPORTED_PERMISSIONS: Record<ModuleType, PermissionType[]> = {
  [ModuleType.DASHBOARD]: [PermissionType.VIEW, PermissionType.CONFIGURE, PermissionType.EXPORT],
  [ModuleType.PROJECTS]: [
    PermissionType.VIEW,
    PermissionType.CREATE,
    PermissionType.EDIT,
    PermissionType.DELETE,
    PermissionType.APPROVE,
    PermissionType.ASSIGN,
    PermissionType.EXPORT,
    PermissionType.ARCHIVE,
    PermissionType.RESTORE,
  ],
  [ModuleType.SCRIPTS]: [
    PermissionType.VIEW,
    PermissionType.CREATE,
    PermissionType.EDIT,
    PermissionType.DELETE,
    PermissionType.APPROVE,
    PermissionType.ASSIGN,
    PermissionType.EXPORT,
    PermissionType.ARCHIVE,
    PermissionType.RESTORE,
  ],
  [ModuleType.GRAPHIC_REQUIREMENTS]: [
    PermissionType.VIEW,
    PermissionType.CREATE,
    PermissionType.EDIT,
    PermissionType.DELETE,
    PermissionType.APPROVE,
    PermissionType.ASSIGN,
    PermissionType.EXPORT,
    PermissionType.ARCHIVE,
    PermissionType.RESTORE,
  ],
  [ModuleType.TASKS]: [
    PermissionType.VIEW,
    PermissionType.CREATE,
    PermissionType.EDIT,
    PermissionType.DELETE,
    PermissionType.ASSIGN,
    PermissionType.EXPORT,
    PermissionType.ARCHIVE,
    PermissionType.RESTORE,
  ],
  [ModuleType.EQUIPMENT]: [
    PermissionType.VIEW,
    PermissionType.CREATE,
    PermissionType.EDIT,
    PermissionType.DELETE,
    PermissionType.APPROVE,
    PermissionType.ASSIGN,
    PermissionType.CONFIGURE,
    PermissionType.EXPORT,
    PermissionType.ARCHIVE,
    PermissionType.RESTORE,
  ],
  [ModuleType.CLIENTS]: [
    PermissionType.VIEW,
    PermissionType.CREATE,
    PermissionType.EDIT,
    PermissionType.DELETE,
    PermissionType.EXPORT,
    PermissionType.ARCHIVE,
    PermissionType.RESTORE,
  ],
  [ModuleType.BRANDS]: [
    PermissionType.VIEW,
    PermissionType.CREATE,
    PermissionType.EDIT,
    PermissionType.DELETE,
    PermissionType.EXPORT,
    PermissionType.ARCHIVE,
    PermissionType.RESTORE,
  ],
  [ModuleType.PRODUCTS]: [
    PermissionType.VIEW,
    PermissionType.CREATE,
    PermissionType.EDIT,
    PermissionType.DELETE,
    PermissionType.EXPORT,
    PermissionType.ARCHIVE,
    PermissionType.RESTORE,
  ],
  [ModuleType.STAFF]: [
    PermissionType.VIEW,
    PermissionType.CREATE,
    PermissionType.EDIT,
    PermissionType.DELETE,
    PermissionType.ASSIGN,
    PermissionType.CONFIGURE,
    PermissionType.EXPORT,
    PermissionType.ARCHIVE,
    PermissionType.RESTORE,
  ],
  [ModuleType.REPORTS]: [
    PermissionType.VIEW,
    PermissionType.EXPORT,
    PermissionType.CONFIGURE,
  ],
  [ModuleType.CALENDAR]: [
    PermissionType.VIEW,
    PermissionType.CREATE,
    PermissionType.EDIT,
    PermissionType.EXPORT,
  ],
  [ModuleType.COMMUNICATIONS]: [
    PermissionType.VIEW,
    PermissionType.CREATE,
    PermissionType.EDIT,
    PermissionType.DELETE,
    PermissionType.ASSIGN,
    PermissionType.ARCHIVE,
    PermissionType.RESTORE,
  ],
  [ModuleType.ACTIVITY_LOGS]: [
    PermissionType.VIEW,
    PermissionType.EXPORT,
  ],
  [ModuleType.SETTINGS]: [
    PermissionType.VIEW,
    PermissionType.EDIT,
    PermissionType.CONFIGURE,
  ],
};

/**
 * Standard Role-Based Access Control (RBAC) Permission Matrix
 * The Media Manager serves as the System Administrator with unrestricted operational access across all modules.
 */
export const ROLE_PERMISSION_MATRIX: Record<Role, Record<ModuleType, PermissionType[]>> = {
  [Role.MEDIA_MANAGER]: {
    [ModuleType.DASHBOARD]: [PermissionType.VIEW, PermissionType.CONFIGURE, PermissionType.EXPORT],
    [ModuleType.PROJECTS]: [
      PermissionType.VIEW,
      PermissionType.CREATE,
      PermissionType.EDIT,
      PermissionType.DELETE,
      PermissionType.APPROVE,
      PermissionType.ASSIGN,
      PermissionType.EXPORT,
      PermissionType.ARCHIVE,
      PermissionType.RESTORE,
    ],
    [ModuleType.SCRIPTS]: [
      PermissionType.VIEW,
      PermissionType.CREATE,
      PermissionType.EDIT,
      PermissionType.DELETE,
      PermissionType.ASSIGN,
      PermissionType.EXPORT,
      PermissionType.ARCHIVE,
      PermissionType.RESTORE,
    ],
    [ModuleType.GRAPHIC_REQUIREMENTS]: [
      PermissionType.VIEW,
      PermissionType.CREATE,
      PermissionType.EDIT,
      PermissionType.DELETE,
      PermissionType.APPROVE,
      PermissionType.ASSIGN,
      PermissionType.EXPORT,
      PermissionType.ARCHIVE,
      PermissionType.RESTORE,
    ],
    [ModuleType.TASKS]: [
      PermissionType.VIEW,
      PermissionType.CREATE,
      PermissionType.EDIT,
      PermissionType.DELETE,
      PermissionType.ASSIGN,
      PermissionType.EXPORT,
      PermissionType.ARCHIVE,
      PermissionType.RESTORE,
    ],
    [ModuleType.EQUIPMENT]: [
      PermissionType.VIEW,
      PermissionType.CREATE,
      PermissionType.EDIT,
      PermissionType.DELETE,
      PermissionType.APPROVE,
      PermissionType.ASSIGN,
      PermissionType.CONFIGURE,
      PermissionType.EXPORT,
      PermissionType.ARCHIVE,
      PermissionType.RESTORE,
    ],
    [ModuleType.CLIENTS]: [
      PermissionType.VIEW,
      PermissionType.CREATE,
      PermissionType.EDIT,
      PermissionType.DELETE,
      PermissionType.EXPORT,
      PermissionType.ARCHIVE,
      PermissionType.RESTORE,
    ],
    [ModuleType.BRANDS]: [
      PermissionType.VIEW,
      PermissionType.CREATE,
      PermissionType.EDIT,
      PermissionType.DELETE,
      PermissionType.EXPORT,
      PermissionType.ARCHIVE,
      PermissionType.RESTORE,
    ],
    [ModuleType.PRODUCTS]: [
      PermissionType.VIEW,
      PermissionType.CREATE,
      PermissionType.EDIT,
      PermissionType.DELETE,
      PermissionType.EXPORT,
      PermissionType.ARCHIVE,
      PermissionType.RESTORE,
    ],
    [ModuleType.STAFF]: [
      PermissionType.VIEW,
      PermissionType.CREATE,
      PermissionType.EDIT,
      PermissionType.DELETE,
      PermissionType.ASSIGN,
      PermissionType.CONFIGURE,
      PermissionType.EXPORT,
      PermissionType.ARCHIVE,
      PermissionType.RESTORE,
    ],
    [ModuleType.REPORTS]: [
      PermissionType.VIEW,
      PermissionType.EXPORT,
      PermissionType.CONFIGURE,
    ],
    [ModuleType.CALENDAR]: [
      PermissionType.VIEW,
      PermissionType.CREATE,
      PermissionType.EDIT,
      PermissionType.EXPORT,
    ],
    [ModuleType.COMMUNICATIONS]: [
      PermissionType.VIEW,
      PermissionType.CREATE,
      PermissionType.EDIT,
      PermissionType.DELETE,
      PermissionType.ASSIGN,
      PermissionType.ARCHIVE,
      PermissionType.RESTORE,
    ],
    [ModuleType.ACTIVITY_LOGS]: [
      PermissionType.VIEW,
      PermissionType.EXPORT,
    ],
    [ModuleType.SETTINGS]: [
      PermissionType.VIEW,
      PermissionType.EDIT,
      PermissionType.CONFIGURE,
    ],
  },
  [Role.TECHNICAL_MANAGER]: {
    [ModuleType.DASHBOARD]: [PermissionType.VIEW, PermissionType.CONFIGURE, PermissionType.EXPORT],
    [ModuleType.PROJECTS]: [
      PermissionType.VIEW,
      PermissionType.EDIT,
      PermissionType.APPROVE,
      PermissionType.EXPORT,
    ],
    [ModuleType.SCRIPTS]: [
      PermissionType.VIEW,
      PermissionType.EDIT,
      PermissionType.APPROVE,
      PermissionType.EXPORT,
    ],
    [ModuleType.GRAPHIC_REQUIREMENTS]: [
      PermissionType.VIEW,
      PermissionType.EDIT,
      PermissionType.APPROVE,
      PermissionType.EXPORT,
    ],
    [ModuleType.TASKS]: [
      PermissionType.VIEW,
      PermissionType.EDIT,
      PermissionType.ASSIGN,
      PermissionType.EXPORT,
    ],
    [ModuleType.EQUIPMENT]: [
      PermissionType.VIEW,
      PermissionType.EDIT,
    ],
    [ModuleType.CLIENTS]: [PermissionType.VIEW, PermissionType.EXPORT],
    [ModuleType.BRANDS]: [PermissionType.VIEW, PermissionType.EXPORT],
    [ModuleType.PRODUCTS]: [PermissionType.VIEW, PermissionType.EXPORT],
    [ModuleType.STAFF]: [PermissionType.VIEW, PermissionType.EXPORT],
    [ModuleType.REPORTS]: [PermissionType.VIEW, PermissionType.EXPORT],
    [ModuleType.CALENDAR]: [PermissionType.VIEW, PermissionType.EXPORT],
    [ModuleType.COMMUNICATIONS]: [
      PermissionType.VIEW,
      PermissionType.CREATE,
      PermissionType.EDIT,
      PermissionType.ASSIGN,
    ],
    [ModuleType.ACTIVITY_LOGS]: [PermissionType.VIEW, PermissionType.EXPORT],
    [ModuleType.SETTINGS]: [PermissionType.VIEW],
  },
  [Role.STAFF]: {
    [ModuleType.DASHBOARD]: [PermissionType.VIEW],
    [ModuleType.PROJECTS]: [PermissionType.VIEW],
    [ModuleType.SCRIPTS]: [PermissionType.VIEW, PermissionType.EDIT],
    [ModuleType.GRAPHIC_REQUIREMENTS]: [PermissionType.VIEW, PermissionType.EDIT],
    [ModuleType.TASKS]: [PermissionType.VIEW, PermissionType.EDIT],
    [ModuleType.EQUIPMENT]: [PermissionType.VIEW],
    [ModuleType.CLIENTS]: [],
    [ModuleType.BRANDS]: [],
    [ModuleType.PRODUCTS]: [],
    [ModuleType.STAFF]: [PermissionType.VIEW],
    [ModuleType.REPORTS]: [PermissionType.VIEW],
    [ModuleType.CALENDAR]: [PermissionType.VIEW],
    [ModuleType.COMMUNICATIONS]: [PermissionType.VIEW, PermissionType.CREATE],
    [ModuleType.ACTIVITY_LOGS]: [],
    [ModuleType.SETTINGS]: [],
  },
  [Role.HR_MANAGER]: {
    [ModuleType.DASHBOARD]: [PermissionType.VIEW, PermissionType.EXPORT],
    [ModuleType.PROJECTS]: [PermissionType.VIEW, PermissionType.EXPORT],
    [ModuleType.SCRIPTS]: [PermissionType.VIEW],
    [ModuleType.GRAPHIC_REQUIREMENTS]: [PermissionType.VIEW],
    [ModuleType.TASKS]: [PermissionType.VIEW, PermissionType.ASSIGN, PermissionType.EXPORT],
    [ModuleType.EQUIPMENT]: [PermissionType.VIEW, PermissionType.EXPORT],
    [ModuleType.CLIENTS]: [PermissionType.VIEW],
    [ModuleType.BRANDS]: [PermissionType.VIEW],
    [ModuleType.PRODUCTS]: [PermissionType.VIEW],
    [ModuleType.STAFF]: [
      PermissionType.VIEW,
      PermissionType.CREATE,
      PermissionType.EDIT,
      PermissionType.DELETE,
      PermissionType.ASSIGN,
      PermissionType.CONFIGURE,
      PermissionType.EXPORT,
      PermissionType.ARCHIVE,
      PermissionType.RESTORE,
    ],
    [ModuleType.REPORTS]: [PermissionType.VIEW, PermissionType.EXPORT],
    [ModuleType.CALENDAR]: [PermissionType.VIEW, PermissionType.EXPORT],
    [ModuleType.COMMUNICATIONS]: [
      PermissionType.VIEW,
      PermissionType.CREATE,
      PermissionType.EDIT,
      PermissionType.ASSIGN,
    ],
    [ModuleType.ACTIVITY_LOGS]: [PermissionType.VIEW, PermissionType.EXPORT],
    [ModuleType.SETTINGS]: [PermissionType.VIEW],
  },
  [Role.FINANCE_MANAGER]: {
    [ModuleType.DASHBOARD]: [PermissionType.VIEW, PermissionType.CONFIGURE, PermissionType.EXPORT],
    [ModuleType.PROJECTS]: [PermissionType.VIEW, PermissionType.APPROVE, PermissionType.EXPORT],
    [ModuleType.SCRIPTS]: [PermissionType.VIEW, PermissionType.EXPORT],
    [ModuleType.GRAPHIC_REQUIREMENTS]: [PermissionType.VIEW, PermissionType.EXPORT],
    [ModuleType.TASKS]: [PermissionType.VIEW, PermissionType.EXPORT],
    [ModuleType.EQUIPMENT]: [PermissionType.VIEW, PermissionType.EXPORT],
    [ModuleType.CLIENTS]: [PermissionType.VIEW, PermissionType.EXPORT],
    [ModuleType.BRANDS]: [PermissionType.VIEW, PermissionType.EXPORT],
    [ModuleType.PRODUCTS]: [PermissionType.VIEW, PermissionType.EXPORT],
    [ModuleType.STAFF]: [PermissionType.VIEW, PermissionType.EXPORT],
    [ModuleType.REPORTS]: [PermissionType.VIEW, PermissionType.EXPORT, PermissionType.CONFIGURE],
    [ModuleType.CALENDAR]: [PermissionType.VIEW, PermissionType.EXPORT],
    [ModuleType.COMMUNICATIONS]: [PermissionType.VIEW, PermissionType.CREATE],
    [ModuleType.ACTIVITY_LOGS]: [PermissionType.VIEW, PermissionType.EXPORT],
    [ModuleType.SETTINGS]: [PermissionType.VIEW, PermissionType.EDIT, PermissionType.CONFIGURE],
  },
  [Role.SOCIAL_MEDIA_MANAGER]: {
    [ModuleType.DASHBOARD]: [PermissionType.VIEW],
    [ModuleType.PROJECTS]: [PermissionType.VIEW],
    [ModuleType.SCRIPTS]: [PermissionType.VIEW, PermissionType.CREATE, PermissionType.EDIT],
    [ModuleType.GRAPHIC_REQUIREMENTS]: [PermissionType.VIEW, PermissionType.CREATE, PermissionType.EDIT],
    [ModuleType.TASKS]: [PermissionType.VIEW],
    [ModuleType.EQUIPMENT]: [PermissionType.VIEW],
    [ModuleType.CLIENTS]: [PermissionType.VIEW],
    [ModuleType.BRANDS]: [PermissionType.VIEW],
    [ModuleType.PRODUCTS]: [PermissionType.VIEW],
    [ModuleType.STAFF]: [],
    [ModuleType.REPORTS]: [PermissionType.VIEW],
    [ModuleType.CALENDAR]: [PermissionType.VIEW, PermissionType.CREATE, PermissionType.EDIT],
    [ModuleType.COMMUNICATIONS]: [PermissionType.VIEW, PermissionType.CREATE],
    [ModuleType.ACTIVITY_LOGS]: [PermissionType.VIEW],
    [ModuleType.SETTINGS]: [],
  },
  [Role.MARKETING_MANAGER]: {
    [ModuleType.DASHBOARD]: [PermissionType.VIEW],
    [ModuleType.PROJECTS]: [PermissionType.VIEW],
    [ModuleType.SCRIPTS]: [PermissionType.VIEW, PermissionType.CREATE, PermissionType.EDIT, PermissionType.APPROVE],
    [ModuleType.GRAPHIC_REQUIREMENTS]: [],
    [ModuleType.TASKS]: [],
    [ModuleType.EQUIPMENT]: [],
    [ModuleType.CLIENTS]: [PermissionType.VIEW],
    [ModuleType.BRANDS]: [PermissionType.VIEW],
    [ModuleType.PRODUCTS]: [PermissionType.VIEW],
    [ModuleType.STAFF]: [],
    [ModuleType.REPORTS]: [PermissionType.VIEW],
    [ModuleType.CALENDAR]: [PermissionType.VIEW, PermissionType.APPROVE],
    [ModuleType.COMMUNICATIONS]: [PermissionType.VIEW, PermissionType.CREATE],
    [ModuleType.ACTIVITY_LOGS]: [],
    [ModuleType.SETTINGS]: [],
  },
  [Role.SALES_MANAGER]: {
    [ModuleType.DASHBOARD]: [PermissionType.VIEW, PermissionType.EXPORT],
    [ModuleType.PROJECTS]: [PermissionType.VIEW, PermissionType.CREATE, PermissionType.EDIT, PermissionType.EXPORT],
    [ModuleType.SCRIPTS]: [PermissionType.VIEW, PermissionType.EXPORT],
    [ModuleType.GRAPHIC_REQUIREMENTS]: [PermissionType.VIEW, PermissionType.EXPORT],
    [ModuleType.TASKS]: [PermissionType.VIEW, PermissionType.EXPORT],
    [ModuleType.EQUIPMENT]: [PermissionType.VIEW, PermissionType.EXPORT],
    [ModuleType.CLIENTS]: [
      PermissionType.VIEW,
      PermissionType.CREATE,
      PermissionType.EDIT,
      PermissionType.DELETE,
      PermissionType.EXPORT,
      PermissionType.ARCHIVE,
      PermissionType.RESTORE,
    ],
    [ModuleType.BRANDS]: [
      PermissionType.VIEW,
      PermissionType.CREATE,
      PermissionType.EDIT,
      PermissionType.DELETE,
      PermissionType.EXPORT,
      PermissionType.ARCHIVE,
      PermissionType.RESTORE,
    ],
    [ModuleType.PRODUCTS]: [
      PermissionType.VIEW,
      PermissionType.CREATE,
      PermissionType.EDIT,
      PermissionType.DELETE,
      PermissionType.EXPORT,
      PermissionType.ARCHIVE,
      PermissionType.RESTORE,
    ],
    [ModuleType.STAFF]: [PermissionType.VIEW, PermissionType.EXPORT],
    [ModuleType.REPORTS]: [PermissionType.VIEW, PermissionType.EXPORT],
    [ModuleType.CALENDAR]: [PermissionType.VIEW, PermissionType.EXPORT],
    [ModuleType.COMMUNICATIONS]: [PermissionType.VIEW, PermissionType.CREATE, PermissionType.EDIT],
    [ModuleType.ACTIVITY_LOGS]: [PermissionType.VIEW, PermissionType.EXPORT],
    [ModuleType.SETTINGS]: [PermissionType.VIEW],
  },
  [Role.CLIENT_COORDINATOR]: {
    [ModuleType.DASHBOARD]: [PermissionType.VIEW],
    [ModuleType.PROJECTS]: [PermissionType.VIEW, PermissionType.EDIT, PermissionType.APPROVE, PermissionType.EXPORT],
    [ModuleType.SCRIPTS]: [PermissionType.VIEW, PermissionType.EDIT, PermissionType.APPROVE, PermissionType.EXPORT],
    [ModuleType.GRAPHIC_REQUIREMENTS]: [PermissionType.VIEW, PermissionType.EDIT, PermissionType.APPROVE, PermissionType.EXPORT],
    [ModuleType.TASKS]: [PermissionType.VIEW, PermissionType.EDIT, PermissionType.EXPORT],
    [ModuleType.EQUIPMENT]: [PermissionType.VIEW],
    [ModuleType.CLIENTS]: [PermissionType.VIEW, PermissionType.CREATE, PermissionType.EDIT, PermissionType.EXPORT],
    [ModuleType.BRANDS]: [PermissionType.VIEW, PermissionType.CREATE, PermissionType.EDIT, PermissionType.EXPORT],
    [ModuleType.PRODUCTS]: [PermissionType.VIEW, PermissionType.CREATE, PermissionType.EDIT, PermissionType.EXPORT],
    [ModuleType.STAFF]: [PermissionType.VIEW],
    [ModuleType.REPORTS]: [PermissionType.VIEW, PermissionType.EXPORT],
    [ModuleType.CALENDAR]: [PermissionType.VIEW, PermissionType.EXPORT],
    [ModuleType.COMMUNICATIONS]: [
      PermissionType.VIEW,
      PermissionType.CREATE,
      PermissionType.EDIT,
      PermissionType.ASSIGN,
    ],
    [ModuleType.ACTIVITY_LOGS]: [PermissionType.VIEW],
    [ModuleType.SETTINGS]: [],
  },
  [Role.ADMINISTRATOR]: {
    [ModuleType.DASHBOARD]: [PermissionType.VIEW, PermissionType.CONFIGURE, PermissionType.EXPORT],
    [ModuleType.PROJECTS]: [
      PermissionType.VIEW,
      PermissionType.CREATE,
      PermissionType.EDIT,
      PermissionType.DELETE,
      PermissionType.APPROVE,
      PermissionType.ASSIGN,
      PermissionType.EXPORT,
      PermissionType.ARCHIVE,
      PermissionType.RESTORE,
    ],
    [ModuleType.SCRIPTS]: [
      PermissionType.VIEW,
      PermissionType.CREATE,
      PermissionType.EDIT,
      PermissionType.DELETE,
      PermissionType.APPROVE,
      PermissionType.ASSIGN,
      PermissionType.EXPORT,
      PermissionType.ARCHIVE,
      PermissionType.RESTORE,
    ],
    [ModuleType.GRAPHIC_REQUIREMENTS]: [
      PermissionType.VIEW,
      PermissionType.CREATE,
      PermissionType.EDIT,
      PermissionType.DELETE,
      PermissionType.APPROVE,
      PermissionType.ASSIGN,
      PermissionType.EXPORT,
      PermissionType.ARCHIVE,
      PermissionType.RESTORE,
    ],
    [ModuleType.TASKS]: [
      PermissionType.VIEW,
      PermissionType.CREATE,
      PermissionType.EDIT,
      PermissionType.DELETE,
      PermissionType.ASSIGN,
      PermissionType.EXPORT,
      PermissionType.ARCHIVE,
      PermissionType.RESTORE,
    ],
    [ModuleType.EQUIPMENT]: [
      PermissionType.VIEW,
      PermissionType.CREATE,
      PermissionType.EDIT,
      PermissionType.DELETE,
      PermissionType.APPROVE,
      PermissionType.ASSIGN,
      PermissionType.CONFIGURE,
      PermissionType.EXPORT,
      PermissionType.ARCHIVE,
      PermissionType.RESTORE,
    ],
    [ModuleType.CLIENTS]: [
      PermissionType.VIEW,
      PermissionType.CREATE,
      PermissionType.EDIT,
      PermissionType.DELETE,
      PermissionType.EXPORT,
      PermissionType.ARCHIVE,
      PermissionType.RESTORE,
    ],
    [ModuleType.BRANDS]: [
      PermissionType.VIEW,
      PermissionType.CREATE,
      PermissionType.EDIT,
      PermissionType.DELETE,
      PermissionType.EXPORT,
      PermissionType.ARCHIVE,
      PermissionType.RESTORE,
    ],
    [ModuleType.PRODUCTS]: [
      PermissionType.VIEW,
      PermissionType.CREATE,
      PermissionType.EDIT,
      PermissionType.DELETE,
      PermissionType.EXPORT,
      PermissionType.ARCHIVE,
      PermissionType.RESTORE,
    ],
    [ModuleType.STAFF]: [
      PermissionType.VIEW,
      PermissionType.CREATE,
      PermissionType.EDIT,
      PermissionType.DELETE,
      PermissionType.ASSIGN,
      PermissionType.CONFIGURE,
      PermissionType.EXPORT,
      PermissionType.ARCHIVE,
      PermissionType.RESTORE,
    ],
    [ModuleType.REPORTS]: [
      PermissionType.VIEW,
      PermissionType.EXPORT,
      PermissionType.CONFIGURE,
    ],
    [ModuleType.CALENDAR]: [
      PermissionType.VIEW,
      PermissionType.CREATE,
      PermissionType.EDIT,
      PermissionType.EXPORT,
    ],
    [ModuleType.COMMUNICATIONS]: [
      PermissionType.VIEW,
      PermissionType.CREATE,
      PermissionType.EDIT,
      PermissionType.DELETE,
      PermissionType.ASSIGN,
      PermissionType.ARCHIVE,
      PermissionType.RESTORE,
    ],
    [ModuleType.ACTIVITY_LOGS]: [
      PermissionType.VIEW,
      PermissionType.EXPORT,
    ],
    [ModuleType.SETTINGS]: [
      PermissionType.VIEW,
      PermissionType.EDIT,
      PermissionType.CONFIGURE,
    ],
  },
};
