import { Role } from '../enums';

export enum ReportType {
  PRODUCTION = 'PRODUCTION',
  GRAPHIC_ANALYTICS = 'GRAPHIC_ANALYTICS',
  PRODUCTIVITY = 'PRODUCTIVITY',
  EMPLOYEE_ANALYTICS = 'EMPLOYEE_ANALYTICS',
  BRANDS = 'BRANDS',
  CLIENTS = 'CLIENTS',
  PRODUCTS = 'PRODUCTS',
  DEPARTMENTS = 'DEPARTMENTS',
  PROJECTS = 'PROJECTS',
  ATTENDANCE_ANALYTICS = 'ATTENDANCE_ANALYTICS',
  EQUIPMENT = 'EQUIPMENT',
  APPROVALS = 'APPROVALS',
  CAPACITY = 'CAPACITY',
  REVISIONS = 'REVISIONS',
  TIMELINES = 'TIMELINES',
  BRAND_REPORTS = 'BRAND_REPORTS',
  TASK_ASSIGNMENTS = 'TASK_ASSIGNMENTS',
  SHOOT_REPORTS = 'SHOOT_REPORTS',
  GRAPHIC_REPORTS = 'GRAPHIC_REPORTS',
  STAFF_WORK_REPORTS = 'STAFF_WORK_REPORTS',
  EQUIPMENT_RENTAL_REPORTS = 'EQUIPMENT_RENTAL_REPORTS',
  PERSONAL_DASHBOARD = 'PERSONAL_DASHBOARD',
  TECHNICAL_DASHBOARD = 'TECHNICAL_DASHBOARD',
}

export const REPORT_ROLE_PERMISSIONS: Record<string, Role[]> = {
  [ReportType.BRAND_REPORTS]: [Role.MARKETING_MANAGER, Role.MEDIA_MANAGER, Role.ADMINISTRATOR],
  [ReportType.TASK_ASSIGNMENTS]: [Role.MARKETING_MANAGER, Role.MEDIA_MANAGER, Role.ADMINISTRATOR],
  [ReportType.SHOOT_REPORTS]: [Role.MEDIA_MANAGER, Role.ADMINISTRATOR],
  [ReportType.GRAPHIC_REPORTS]: [Role.MEDIA_MANAGER, Role.ADMINISTRATOR],
  [ReportType.STAFF_WORK_REPORTS]: [Role.MEDIA_MANAGER, Role.ADMINISTRATOR],
  [ReportType.EQUIPMENT_RENTAL_REPORTS]: [Role.MEDIA_MANAGER, Role.ADMINISTRATOR],

  [ReportType.PRODUCTION]: [Role.MEDIA_MANAGER, Role.ADMINISTRATOR],
  [ReportType.GRAPHIC_ANALYTICS]: [Role.MEDIA_MANAGER, Role.ADMINISTRATOR],
  [ReportType.PRODUCTIVITY]: [Role.MEDIA_MANAGER, Role.ADMINISTRATOR],
  [ReportType.EMPLOYEE_ANALYTICS]: [Role.MEDIA_MANAGER, Role.ADMINISTRATOR],
  [ReportType.BRANDS]: [Role.MARKETING_MANAGER, Role.MEDIA_MANAGER, Role.ADMINISTRATOR],
  [ReportType.CLIENTS]: [Role.MEDIA_MANAGER, Role.ADMINISTRATOR],
  [ReportType.PRODUCTS]: [Role.MEDIA_MANAGER, Role.ADMINISTRATOR],
  [ReportType.DEPARTMENTS]: [Role.MEDIA_MANAGER, Role.ADMINISTRATOR],
  [ReportType.PROJECTS]: [Role.MEDIA_MANAGER, Role.ADMINISTRATOR],
  [ReportType.ATTENDANCE_ANALYTICS]: [Role.MEDIA_MANAGER, Role.ADMINISTRATOR],
  [ReportType.TIMELINES]: [Role.MEDIA_MANAGER, Role.ADMINISTRATOR],

  [ReportType.EQUIPMENT]: [Role.MEDIA_MANAGER, Role.TECHNICAL_MANAGER, Role.ADMINISTRATOR],
  [ReportType.APPROVALS]: [Role.MEDIA_MANAGER, Role.TECHNICAL_MANAGER, Role.ADMINISTRATOR],
  [ReportType.CAPACITY]: [Role.MEDIA_MANAGER, Role.TECHNICAL_MANAGER, Role.ADMINISTRATOR],
  [ReportType.REVISIONS]: [Role.MEDIA_MANAGER, Role.TECHNICAL_MANAGER, Role.ADMINISTRATOR],
  [ReportType.TECHNICAL_DASHBOARD]: [Role.MEDIA_MANAGER, Role.TECHNICAL_MANAGER, Role.ADMINISTRATOR],

  [ReportType.PERSONAL_DASHBOARD]: [Role.MEDIA_MANAGER, Role.TECHNICAL_MANAGER, Role.STAFF, Role.ADMINISTRATOR],
};

export function isReportAllowedForRole(reportKey: string, role: string): boolean {
  if (!role) return false;
  if (role === Role.ADMINISTRATOR || role === 'ADMIN') return true;
  const allowed = REPORT_ROLE_PERMISSIONS[reportKey];
  if (!allowed) return false;
  return allowed.includes(role as Role);
}
